"use client";

import { useEffect, useState } from "react";
import {
  ChevronDown,
  Clock,
  ExternalLink,
  Film,
  Paperclip,
  Play,
  Plus,
  Scissors,
} from "lucide-react";
import type { ValidatedIssue } from "@/types/analysis";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";

type IssueType = "Bug" | "Task" | "Spike" | "Story";
type Priority = "Highest" | "High" | "Medium" | "Low" | "Lowest";

interface Props {
  issue: ValidatedIssue | null;
  onClose: () => void;
}

const JIRA_BASE_URL =
  process.env.NEXT_PUBLIC_JIRA_BASE_URL || "https://your-company.atlassian.net";
const JIRA_PROJECT_ID = process.env.NEXT_PUBLIC_JIRA_PROJECT_ID || "10000";

const PRIORITY_CONFIG: Record<
  Priority,
  { wrap: string; icon: string; iconColor: string }
> = {
  Highest: {
    wrap: "bg-red-50 text-red-700 border-red-200",
    icon: "⇈",
    iconColor: "text-red-600",
  },
  High: {
    wrap: "bg-orange-50 text-orange-700 border-orange-200",
    icon: "↑",
    iconColor: "text-orange-600",
  },
  Medium: {
    wrap: "bg-amber-50 text-amber-700 border-amber-200",
    icon: "=",
    iconColor: "text-amber-600",
  },
  Low: {
    wrap: "bg-sky-50 text-sky-700 border-sky-200",
    icon: "↓",
    iconColor: "text-sky-600",
  },
  Lowest: {
    wrap: "bg-slate-50 text-slate-700 border-slate-200",
    icon: "⇊",
    iconColor: "text-slate-500",
  },
};

const ISSUE_TYPE_CONFIG: Record<IssueType, { bg: string; icon: string }> = {
  Bug: { bg: "bg-red-500", icon: "●" },
  Task: { bg: "bg-blue-500", icon: "✓" },
  Spike: { bg: "bg-purple-500", icon: "◆" },
  Story: { bg: "bg-green-500", icon: "▲" },
};

const CATEGORY_COLORS: Record<string, string> = {
  navigation: "bg-purple-50 text-purple-700 border-purple-200",
  ui_element: "bg-blue-50 text-blue-700 border-blue-200",
  user_flow: "bg-emerald-50 text-emerald-700 border-emerald-200",
  accessibility: "bg-pink-50 text-pink-700 border-pink-200",
  interaction_delay: "bg-orange-50 text-orange-700 border-orange-200",
  unclear_messaging: "bg-teal-50 text-teal-700 border-teal-200",
};

function labelColor(label: string): string {
  return (
    CATEGORY_COLORS[label] ??
    "bg-slate-50 text-slate-700 border-slate-200"
  );
}

function verdictToIssueType(verdict: ValidatedIssue["verdict"]): IssueType {
  if (verdict === "genuine_bug") return "Bug";
  if (verdict === "stylistic_choice") return "Task";
  return "Spike";
}

function severityToPriority(severity: ValidatedIssue["severity"]): Priority {
  if (severity === "critical") return "Highest";
  if (severity === "major") return "High";
  return "Medium";
}

function defaultSummary(description: string): string {
  const first = description.split(/(?<=[.!?])\s/)[0]?.trim() ?? description;
  if (first.length <= 80) return first;
  return first.slice(0, 79).trimEnd() + "…";
}

function buildDescription(issue: ValidatedIssue): string {
  const lines: string[] = [];
  lines.push("h2. Observed issue");
  lines.push(issue.description);
  lines.push("");
  lines.push("h2. Category");
  lines.push(issue.category.replace(/_/g, " "));
  lines.push("");
  lines.push("h2. AI Critic Verdict");
  lines.push(
    `*${issue.verdict.replace(/_/g, " ")}* — ${issue.criticReasoning}`
  );
  if (issue.timestamp) {
    lines.push("");
    lines.push("h2. Reproduce at");
    lines.push(issue.timestamp);
  }
  lines.push("");
  lines.push("----");
  lines.push("_Generated by Video UX Analyzer_");
  return lines.join("\n");
}

function parseTimestamp(ts: string): number {
  const parts = ts.split(":").map(Number);
  if (parts.length === 3)
    return (parts[0] ?? 0) * 3600 + (parts[1] ?? 0) * 60 + (parts[2] ?? 0);
  if (parts.length === 2) return (parts[0] ?? 0) * 60 + (parts[1] ?? 0);
  return parseFloat(ts) || 0;
}

function formatTimestamp(seconds: number): string {
  const total = Math.max(0, Math.floor(seconds));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  if (h > 0)
    return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}

function JiraIcon() {
  return (
    <svg viewBox="0 0 32 32" className="w-8 h-8 shrink-0">
      <defs>
        <linearGradient id="jiraGrad1" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#2684FF" />
          <stop offset="100%" stopColor="#0052CC" />
        </linearGradient>
        <linearGradient id="jiraGrad2" x1="100%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stopColor="#2684FF" />
          <stop offset="100%" stopColor="#0052CC" />
        </linearGradient>
      </defs>
      <path
        d="M16 3 L28 15 L16 27 L13 24 L22 15 L13 6 Z"
        fill="url(#jiraGrad1)"
      />
      <path
        d="M13 6 L22 15 L13 24 L4 15 Z"
        fill="url(#jiraGrad2)"
        opacity="0.9"
      />
    </svg>
  );
}

function SnippetMock({
  anchorSeconds,
  anchorLabel,
}: {
  anchorSeconds: number;
  anchorLabel: string;
}) {
  const defaultStart = Math.max(0, anchorSeconds - 3);
  const defaultEnd = anchorSeconds + 3;
  const [start, setStart] = useState(formatTimestamp(defaultStart));
  const [end, setEnd] = useState(formatTimestamp(defaultEnd));

  const duration = Math.max(
    0,
    parseTimestamp(end) - parseTimestamp(start)
  );

  return (
    <div className="space-y-4">
      <div className="rounded-xl border border-dashed border-border bg-muted/20 p-5 space-y-4">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
            <Film className="w-5 h-5 text-primary" />
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-medium text-foreground">
              Video snippet
            </p>
            <p className="text-xs text-muted-foreground mt-0.5">
              Clip a segment around{" "}
              <span className="text-primary font-medium">{anchorLabel}</span>{" "}
              to give reviewers context.
            </p>
          </div>
          <span className="text-[10px] px-1.5 py-0.5 rounded bg-muted text-muted-foreground border border-border shrink-0">
            MOCK
          </span>
        </div>

        {/* Timeline bar */}
        <div className="relative h-2 rounded-full bg-muted overflow-hidden">
          <div
            className="absolute inset-y-0 bg-primary/50"
            style={{ left: "25%", right: "25%" }}
          />
          <div
            className="absolute top-1/2 w-3 h-3 rounded-full bg-primary border-2 border-card -translate-y-1/2"
            style={{ left: "calc(25% - 6px)" }}
          />
          <div
            className="absolute top-1/2 w-3 h-3 rounded-full bg-primary border-2 border-card -translate-y-1/2"
            style={{ right: "calc(25% - 6px)" }}
          />
        </div>

        <div className="grid grid-cols-3 gap-3">
          <div>
            <label className="block text-[10px] font-semibold text-muted-foreground mb-1 uppercase tracking-wider">
              Start
            </label>
            <input
              type="text"
              value={start}
              onChange={(e) => setStart(e.target.value)}
              className="w-full px-2 py-1.5 bg-background border border-border rounded-md text-xs text-foreground font-mono focus:border-primary focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-[10px] font-semibold text-muted-foreground mb-1 uppercase tracking-wider">
              End
            </label>
            <input
              type="text"
              value={end}
              onChange={(e) => setEnd(e.target.value)}
              className="w-full px-2 py-1.5 bg-background border border-border rounded-md text-xs text-foreground font-mono focus:border-primary focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-[10px] font-semibold text-muted-foreground mb-1 uppercase tracking-wider">
              Duration
            </label>
            <div className="w-full px-2 py-1.5 bg-muted/40 border border-border rounded-md text-xs text-muted-foreground font-mono flex items-center gap-1">
              <Clock className="w-3 h-3" />
              {duration}s
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2 pt-1">
          <Button
            size="sm"
            variant="outline"
            disabled
            title="Coming soon"
            className="gap-1.5"
          >
            <Play className="w-3.5 h-3.5" />
            Preview
          </Button>
          <Button
            size="sm"
            variant="secondary"
            disabled
            title="Coming soon"
            className="gap-1.5"
          >
            <Scissors className="w-3.5 h-3.5" />
            Clip &amp; Attach
          </Button>
          <span className="text-[10px] text-muted-foreground ml-auto">
            Attachment upload coming soon
          </span>
        </div>
      </div>

      <button
        disabled
        className="w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-dashed border-border text-xs text-muted-foreground hover:border-primary/50 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
      >
        <Plus className="w-3.5 h-3.5" />
        Add another snippet
      </button>

      <div className="flex items-center gap-2 text-[11px] text-muted-foreground">
        <Paperclip className="w-3 h-3" />
        <span>0 attachments · No files will be uploaded yet</span>
      </div>
    </div>
  );
}

export default function JiraTicketModal({ issue, onClose }: Props) {
  const open = issue !== null;

  // Keep last non-null issue so the modal retains its content while animating closed.
  const [cached, setCached] = useState<ValidatedIssue | null>(issue);
  if (issue && issue.id !== cached?.id) setCached(issue);
  const current = issue ?? cached;

  const [summary, setSummary] = useState("");
  const [issueType, setIssueType] = useState<IssueType>("Bug");
  const [priority, setPriority] = useState<Priority>("Medium");
  const [labels, setLabels] = useState<string[]>([]);
  const [description, setDescription] = useState("");
  const [newLabel, setNewLabel] = useState("");

  // Reset form state whenever a new issue opens the modal.
  useEffect(() => {
    if (!issue) return;
    setSummary(defaultSummary(issue.description));
    setIssueType(verdictToIssueType(issue.verdict));
    setPriority(severityToPriority(issue.severity));
    setLabels([issue.category]);
    setDescription(buildDescription(issue));
    setNewLabel("");
  }, [issue]);

  const handleAddLabel = () => {
    const trimmed = newLabel.trim().toLowerCase().replace(/\s+/g, "_");
    if (trimmed && !labels.includes(trimmed)) {
      setLabels([...labels, trimmed]);
    }
    setNewLabel("");
  };

  const handleRemoveLabel = (label: string) => {
    setLabels(labels.filter((l) => l !== label));
  };

  const handleSubmit = () => {
    const url = new URL(
      `${JIRA_BASE_URL}/secure/CreateIssueDetails!init.jspa`
    );
    url.searchParams.set("pid", JIRA_PROJECT_ID);
    url.searchParams.set("issuetype", issueType);
    url.searchParams.set("summary", summary);
    url.searchParams.set("description", description);
    url.searchParams.set("priority", priority);
    if (labels.length) url.searchParams.set("labels", labels.join(","));
    window.open(url.toString(), "_blank", "noopener,noreferrer");
    onClose();
  };

  const pCfg = PRIORITY_CONFIG[priority];
  const tCfg = ISSUE_TYPE_CONFIG[issueType];

  const anchorSeconds = current?.timestamp
    ? parseTimestamp(current.timestamp)
    : 0;
  const anchorLabel = current?.timestamp ?? "0:00";

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent
        showCloseButton={false}
        className="p-0 gap-0"
      >
        {/* Header with Jira breadcrumb */}
        <div className="flex items-center gap-3 px-6 py-4 border-b border-border bg-card/60">
          <JiraIcon />
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <span className="text-[#4c9aff] font-medium">UX Project</span>
              <span className="text-muted-foreground/60">/</span>
              <span>Analysis</span>
            </div>
            <DialogTitle className="text-sm mt-0.5">Create Issue</DialogTitle>
            <DialogDescription className="sr-only">
              Review and edit the Jira ticket details before creation.
            </DialogDescription>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto px-6 py-5">
          <Tabs defaultValue="details" className="w-full">
            <TabsList>
              <TabsTrigger value="details">Details</TabsTrigger>
              <TabsTrigger value="attachments" className="gap-1.5">
                <Paperclip className="w-3 h-3" />
                Attachments
              </TabsTrigger>
            </TabsList>

            <TabsContent value="details" className="space-y-5">
              {/* Summary */}
              <div>
                <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
                  Summary <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  value={summary}
                  onChange={(e) => setSummary(e.target.value)}
                  className="w-full px-3 py-2 bg-background border border-border rounded-lg text-sm text-foreground focus:border-primary focus:ring-1 focus:ring-primary focus:outline-none transition-colors"
                />
              </div>

              {/* Type & Priority row */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
                    Issue Type
                  </label>
                  <div className="flex items-center gap-2 px-3 py-2 bg-background border border-border rounded-lg focus-within:border-primary transition-colors">
                    <span
                      className={`w-5 h-5 rounded flex items-center justify-center text-[10px] text-white ${tCfg.bg}`}
                    >
                      {tCfg.icon}
                    </span>
                    <select
                      value={issueType}
                      onChange={(e) =>
                        setIssueType(e.target.value as IssueType)
                      }
                      className="flex-1 bg-transparent text-sm text-foreground focus:outline-none appearance-none cursor-pointer"
                    >
                      <option value="Bug" className="bg-card">Bug</option>
                      <option value="Task" className="bg-card">Task</option>
                      <option value="Spike" className="bg-card">Spike</option>
                      <option value="Story" className="bg-card">Story</option>
                    </select>
                    <ChevronDown className="w-4 h-4 text-muted-foreground" />
                  </div>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
                    Priority
                  </label>
                  <div
                    className={`flex items-center gap-2 px-3 py-2 border rounded-lg transition-colors ${pCfg.wrap}`}
                  >
                    <span
                      className={`font-bold text-base leading-none ${pCfg.iconColor}`}
                    >
                      {pCfg.icon}
                    </span>
                    <select
                      value={priority}
                      onChange={(e) => setPriority(e.target.value as Priority)}
                      className="flex-1 bg-transparent text-sm focus:outline-none appearance-none cursor-pointer font-medium"
                    >
                      <option value="Highest" className="bg-card text-foreground">Highest</option>
                      <option value="High" className="bg-card text-foreground">High</option>
                      <option value="Medium" className="bg-card text-foreground">Medium</option>
                      <option value="Low" className="bg-card text-foreground">Low</option>
                      <option value="Lowest" className="bg-card text-foreground">Lowest</option>
                    </select>
                    <ChevronDown className={`w-4 h-4 ${pCfg.iconColor}`} />
                  </div>
                </div>
              </div>

              {/* Labels */}
              <div>
                <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
                  Labels
                </label>
                <div className="flex flex-wrap items-center gap-2 px-3 py-2 bg-background border border-border rounded-lg min-h-[2.5rem] focus-within:border-primary transition-colors">
                  {labels.map((l) => (
                    <span
                      key={l}
                      className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-md text-xs font-medium border ${labelColor(l)}`}
                    >
                      {l.replace(/_/g, " ")}
                      <button
                        type="button"
                        onClick={() => handleRemoveLabel(l)}
                        className="hover:text-foreground leading-none opacity-60 hover:opacity-100 transition-opacity"
                        aria-label={`Remove ${l}`}
                      >
                        ×
                      </button>
                    </span>
                  ))}
                  <input
                    type="text"
                    value={newLabel}
                    onChange={(e) => setNewLabel(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault();
                        handleAddLabel();
                      } else if (
                        e.key === "Backspace" &&
                        !newLabel &&
                        labels.length
                      ) {
                        handleRemoveLabel(labels[labels.length - 1]);
                      }
                    }}
                    onBlur={handleAddLabel}
                    placeholder={labels.length ? "" : "Add label..."}
                    className="flex-1 min-w-[80px] bg-transparent text-xs text-foreground focus:outline-none"
                  />
                </div>
              </div>

              {/* Description */}
              <div>
                <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
                  Description
                </label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={9}
                  className="w-full px-3 py-2 bg-background border border-border rounded-lg text-xs text-foreground font-mono leading-relaxed focus:border-primary focus:ring-1 focus:ring-primary focus:outline-none resize-y"
                />
              </div>

              {/* Reporter / Assignee */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
                    Reporter
                  </label>
                  <div className="flex items-center gap-2 px-3 py-2 bg-background border border-border rounded-lg">
                    <div className="w-6 h-6 rounded-full bg-gradient-to-br from-violet-500 to-violet-700 flex items-center justify-center text-xs font-bold text-white">
                      U
                    </div>
                    <span className="text-sm text-foreground">
                      UX Analyzer Bot
                    </span>
                  </div>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
                    Assignee
                  </label>
                  <div className="flex items-center gap-2 px-3 py-2 bg-background border border-border rounded-lg">
                    <div className="w-6 h-6 rounded-full bg-muted border border-dashed border-muted-foreground/50 flex items-center justify-center text-xs text-muted-foreground">
                      ?
                    </div>
                    <span className="text-sm text-muted-foreground">
                      Unassigned
                    </span>
                  </div>
                </div>
              </div>
            </TabsContent>

            <TabsContent value="attachments">
              <SnippetMock
                anchorSeconds={anchorSeconds}
                anchorLabel={anchorLabel}
              />
            </TabsContent>
          </Tabs>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-border bg-card/60 flex items-center justify-between gap-3">
          <p className="text-xs text-muted-foreground hidden sm:flex items-center gap-1.5">
            <ExternalLink className="w-3 h-3" />
            Opens Jira in a new tab with fields pre-filled
          </p>
          <div className="flex gap-2 ml-auto">
            <Button variant="ghost" onClick={onClose}>
              Cancel
            </Button>
            <Button onClick={handleSubmit} disabled={!summary.trim()}>
              Create Issue
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
